version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloworldsam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hhlqwy8868o7"
s3_prefix = "helloworldsam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
